export var NOTIFICATION_TYPE;
(function (NOTIFICATION_TYPE) {
    NOTIFICATION_TYPE["CONTRACT_CREATED"] = "CONTRACT_CREATED";
    NOTIFICATION_TYPE["CONTRACT_ACCEPTED"] = "CONTRACT_ACCEPTED";
    NOTIFICATION_TYPE["CONTRACT_REJECTED"] = "CONTRACT_REJECTED";
    NOTIFICATION_TYPE["CONTRACT_UPDATED"] = "CONTRACT_UPDATED";
    NOTIFICATION_TYPE["TRANSPORT_STARTED"] = "TRANSPORT_STARTED";
    NOTIFICATION_TYPE["TRANSPORT_FINISHED"] = "TRANSPORT_FINISHED";
    NOTIFICATION_TYPE["STORAGE_STARTED"] = "STORAGE_STARTED";
    NOTIFICATION_TYPE["STORAGE_FINISHED"] = "STORAGE_FINISHED";
    NOTIFICATION_TYPE["PRODUCT_SHARED"] = "PRODUCT_SHARED";
    NOTIFICATION_TYPE["PRODUCT_UNSHARED"] = "PRODUCT_UNSHARED";
    NOTIFICATION_TYPE["TRANSFER_OWNERSHIP_CREATED"] = "TRANSFER_OWNERSHIP_CREATED";
    NOTIFICATION_TYPE["TRANSFER_OWNERSHIP_ACCEPTED"] = "TRANSFER_OWNERSHIP_ACCEPTED";
    NOTIFICATION_TYPE["TRANSFER_OWNERSHIP_CHANGE_REQUESTED"] = "TRANSFER_OWNERSHIP_CHANGE_REQUESTED";
    NOTIFICATION_TYPE["TRANSFER_OWNERSHIP_FINISHED"] = "TRANSFER_OWNERSHIP_FINISHED";
    NOTIFICATION_TYPE["TRANSFER_CUSTODY_CREATED"] = "TRANSFER_CUSTODY_CREATED";
    NOTIFICATION_TYPE["TRANSFER_CUSTODY_ACCEPTED"] = "TRANSFER_CUSTODY_ACCEPTED";
    NOTIFICATION_TYPE["TRANSFER_CUSTODY_CHANGE_REQUESTED"] = "TRANSFER_CUSTODY_CHANGE_REQUESTED";
    NOTIFICATION_TYPE["TRANSFER_CUSTODY_FINISHED"] = "TRANSFER_CUSTODY_FINISHED";
    NOTIFICATION_TYPE["TRANSFER_OWNERSHIP_UPDATED"] = "TRANSFER_OWNERSHIP_UPDATED";
    NOTIFICATION_TYPE["TRANSFER_CUSTODY_UPDATED"] = "TRANSFER_CUSTODY_UPDATED";
})(NOTIFICATION_TYPE || (NOTIFICATION_TYPE = {}));
export const ActionableNotifications = new Map([
    [NOTIFICATION_TYPE.CONTRACT_CREATED, true],
    [NOTIFICATION_TYPE.CONTRACT_ACCEPTED, false],
    [NOTIFICATION_TYPE.TRANSPORT_STARTED, false],
    [NOTIFICATION_TYPE.TRANSPORT_FINISHED, false],
    [NOTIFICATION_TYPE.STORAGE_STARTED, false],
    [NOTIFICATION_TYPE.STORAGE_FINISHED, false],
    [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_CREATED, true],
    [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_ACCEPTED, true],
    [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_CHANGE_REQUESTED, true],
    [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_FINISHED, false],
    [NOTIFICATION_TYPE.TRANSFER_CUSTODY_CREATED, true],
    [NOTIFICATION_TYPE.TRANSFER_CUSTODY_ACCEPTED, true],
    [NOTIFICATION_TYPE.TRANSFER_CUSTODY_CHANGE_REQUESTED, true],
    [NOTIFICATION_TYPE.TRANSFER_CUSTODY_FINISHED, false],
    [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_UPDATED, true],
    [NOTIFICATION_TYPE.TRANSFER_CUSTODY_UPDATED, true]
]);
export var SOCKET_EVENT_NAME;
(function (SOCKET_EVENT_NAME) {
    SOCKET_EVENT_NAME["CONTRACTS_CHANGED"] = "CONTRACTS_CHANGED";
    SOCKET_EVENT_NAME["NOTIFICATIONS_CHANGED"] = "NOTIFICATIONS_CHANGED";
    SOCKET_EVENT_NAME["PRODUCTS_CHANGED"] = "PRODUCTS_CHANGED";
    SOCKET_EVENT_NAME["ACTIONS_CHANGED"] = "ACTIONS_CHANGED";
    SOCKET_EVENT_NAME["TRANSPORT_CHANGED"] = "TRANSPORT_CHANGED";
    SOCKET_EVENT_NAME["STORAGE_CHANGED"] = "STORAGE_CHANGED";
})(SOCKET_EVENT_NAME || (SOCKET_EVENT_NAME = {}));
