export enum NOTIFICATION_TYPE {
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_ACCEPTED = 'CONTRACT_ACCEPTED',
  CONTRACT_REJECTED = 'CONTRACT_REJECTED',
  CONTRACT_UPDATED = 'CONTRACT_UPDATED',
  TRANSPORT_STARTED = 'TRANSPORT_STARTED',
  TRANSPORT_FINISHED = 'TRANSPORT_FINISHED',
  STORAGE_STARTED = 'STORAGE_STARTED',
  STORAGE_FINISHED = 'STORAGE_FINISHED',
  PRODUCT_SHARED = 'PRODUCT_SHARED',
  PRODUCT_UNSHARED = 'PRODUCT_UNSHARED',
  TRANSFER_OWNERSHIP_CREATED = 'TRANSFER_OWNERSHIP_CREATED',
  TRANSFER_OWNERSHIP_ACCEPTED = 'TRANSFER_OWNERSHIP_ACCEPTED',
  TRANSFER_OWNERSHIP_CHANGE_REQUESTED = 'TRANSFER_OWNERSHIP_CHANGE_REQUESTED',
  TRANSFER_OWNERSHIP_FINISHED = 'TRANSFER_OWNERSHIP_FINISHED',
  TRANSFER_CUSTODY_CREATED = 'TRANSFER_CUSTODY_CREATED',
  TRANSFER_CUSTODY_ACCEPTED = 'TRANSFER_CUSTODY_ACCEPTED',
  TRANSFER_CUSTODY_CHANGE_REQUESTED = 'TRANSFER_CUSTODY_CHANGE_REQUESTED',
  TRANSFER_CUSTODY_FINISHED = 'TRANSFER_CUSTODY_FINISHED',
  TRANSFER_OWNERSHIP_UPDATED = 'TRANSFER_OWNERSHIP_UPDATED',
  TRANSFER_CUSTODY_UPDATED = 'TRANSFER_CUSTODY_UPDATED'
}

export const ActionableNotifications = new Map<string, boolean>([
  [NOTIFICATION_TYPE.CONTRACT_CREATED, true],
  [NOTIFICATION_TYPE.CONTRACT_ACCEPTED, false],
  [NOTIFICATION_TYPE.TRANSPORT_STARTED, false],
  [NOTIFICATION_TYPE.TRANSPORT_FINISHED, false],
  [NOTIFICATION_TYPE.STORAGE_STARTED, false],
  [NOTIFICATION_TYPE.STORAGE_FINISHED, false],
  [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_CREATED, true],
  [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_ACCEPTED, true],
  [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_CHANGE_REQUESTED, true],
  [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_FINISHED, false],
  [NOTIFICATION_TYPE.TRANSFER_CUSTODY_CREATED, true],
  [NOTIFICATION_TYPE.TRANSFER_CUSTODY_ACCEPTED, true],
  [NOTIFICATION_TYPE.TRANSFER_CUSTODY_CHANGE_REQUESTED, true],
  [NOTIFICATION_TYPE.TRANSFER_CUSTODY_FINISHED, false],
  [NOTIFICATION_TYPE.TRANSFER_OWNERSHIP_UPDATED, true],
  [NOTIFICATION_TYPE.TRANSFER_CUSTODY_UPDATED, true]
])

export enum SOCKET_EVENT_NAME {
  CONTRACTS_CHANGED = 'CONTRACTS_CHANGED',
  NOTIFICATIONS_CHANGED = 'NOTIFICATIONS_CHANGED',
  PRODUCTS_CHANGED = 'PRODUCTS_CHANGED',
  ACTIONS_CHANGED = 'ACTIONS_CHANGED',
  TRANSPORT_CHANGED = 'TRANSPORT_CHANGED',
  STORAGE_CHANGED = 'STORAGE_CHANGED'
}
