"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SOCKET_EVENT_NAME = void 0;
var SOCKET_EVENT_NAME;
(function (SOCKET_EVENT_NAME) {
    SOCKET_EVENT_NAME["CONTRACTS_CHANGED"] = "CONTRACTS_CHANGED";
    SOCKET_EVENT_NAME["NOTIFICATIONS_CHANGED"] = "NOTIFICATIONS_CHANGED";
    SOCKET_EVENT_NAME["PRODUCTS_CHANGED"] = "PRODUCTS_CHANGED";
    SOCKET_EVENT_NAME["ACTIONS_CHANGED"] = "ACTIONS_CHANGED";
    SOCKET_EVENT_NAME["TRANSPORT_CHANGED"] = "TRANSPORT_CHANGED";
    SOCKET_EVENT_NAME["STORAGE_CHANGED"] = "STORAGE_CHANGED";
})(SOCKET_EVENT_NAME || (exports.SOCKET_EVENT_NAME = SOCKET_EVENT_NAME = {}));
