export declare enum SOCKET_EVENT_NAME {
    CONTRACTS_CHANGED = "CONTRACTS_CHANGED",
    NOTIFICATIONS_CHANGED = "NOTIFICATIONS_CHANGED",
    PRODUCTS_CHANGED = "PRODUCTS_CHANGED",
    ACTIONS_CHANGED = "ACTIONS_CHANGED",
    TRANSPORT_CHANGED = "TRANSPORT_CHANGED",
    STORAGE_CHANGED = "STORAGE_CHANGED"
}
