"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DELIVERY_MONTH = void 0;
var DELIVERY_MONTH;
(function (DELIVERY_MONTH) {
    DELIVERY_MONTH["JANUARY"] = "JANUARY";
    DELIVERY_MONTH["FEBRUARY"] = "FEBRUARY";
    DELIVERY_MONTH["MARCH"] = "MARCH";
    DELIVERY_MONTH["APRIL"] = "APRIL";
    DELIVERY_MONTH["MAY"] = "MAY";
    DELIVERY_MONTH["JUNE"] = "JUNE";
    DELIVERY_MONTH["JULY"] = "JULY";
    DELIVERY_MONTH["AUGUST"] = "AUGUST";
    DELIVERY_MONTH["SEPTEMBER"] = "SEPTEMBER";
    DELIVERY_MONTH["OCTOBER"] = "OCTOBER";
    DELIVERY_MONTH["NOVEMBER"] = "NOVEMBER";
    DELIVERY_MONTH["DECEMBER"] = "DECEMBER";
})(DELIVERY_MONTH || (exports.DELIVERY_MONTH = DELIVERY_MONTH = {}));
