"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DELIVERY_STATUS = void 0;
var DELIVERY_STATUS;
(function (DELIVERY_STATUS) {
    DELIVERY_STATUS["SCHEDULED"] = "SCHEDULED";
    DELIVERY_STATUS["IN_TRANSIT"] = "IN_TRANSIT";
    DELIVERY_STATUS["TRANSPORT_COMPLETED"] = "TRANSPORT_COMPLETED";
})(DELIVERY_STATUS || (exports.DELIVERY_STATUS = DELIVERY_STATUS = {}));
