export declare enum CURRENT_EVENT_TYPE {
    CREATE_PRODUCT = "CREATE_PRODUCT",
    START_TRANSPORT = "START_TRANSPORT",
    END_TRANSPORT = "END_TRANSPORT",
    TRANSFORMATION_UPGRADE = "TRANSFORMATION_UPGRADE",
    TRANSFORMATION_SPLIT = "TRANSFORMATION_SPLIT",
    TRANSFORMATION_POOL = "TRANSFORMATION_POOL",
    TRANSFORMATION_BLEND = "TRANSFORMATION_BLEND",
    TRANSFORMATION_REFINE = "TRANSFORMATION_REFINE",
    OWNERSHIP_TRANSFERED = "OWNERSHIP_TRANSFERED",
    DELIVERY_SCHEDULED = "DELIVERY_SCHEDULED"
}
export declare enum EVENT_TYPE {
    CREATE = "CREATE",
    STARTTRANSPORT = "STARTTRANSPORT",
    ENDTRANSPORT = "ENDTRANSPORT",
    UPGRADE = "UPGRADE",
    REFINE = "REFINE",
    POOL = "POOL",
    BLEND = "BLEND",
    SPLIT = "SPLIT",
    DELIVERY_SCHEDULED = "DELIVERY_SCHEDULED"
}
