"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENT_TYPE = exports.CURRENT_EVENT_TYPE = void 0;
var CURRENT_EVENT_TYPE;
(function (CURRENT_EVENT_TYPE) {
    CURRENT_EVENT_TYPE["CREATE_PRODUCT"] = "CREATE_PRODUCT";
    CURRENT_EVENT_TYPE["START_TRANSPORT"] = "START_TRANSPORT";
    CURRENT_EVENT_TYPE["END_TRANSPORT"] = "END_TRANSPORT";
    CURRENT_EVENT_TYPE["TRANSFORMATION_UPGRADE"] = "TRANSFORMATION_UPGRADE";
    CURRENT_EVENT_TYPE["TRANSFORMATION_SPLIT"] = "TRANSFORMATION_SPLIT";
    CURRENT_EVENT_TYPE["TRANSFORMATION_POOL"] = "TRANSFORMATION_POOL";
    CURRENT_EVENT_TYPE["TRANSFORMATION_BLEND"] = "TRANSFORMATION_BLEND";
    CURRENT_EVENT_TYPE["TRANSFORMATION_REFINE"] = "TRANSFORMATION_REFINE";
    CURRENT_EVENT_TYPE["OWNERSHIP_TRANSFERED"] = "OWNERSHIP_TRANSFERED";
})(CURRENT_EVENT_TYPE = exports.CURRENT_EVENT_TYPE || (exports.CURRENT_EVENT_TYPE = {}));
var EVENT_TYPE;
(function (EVENT_TYPE) {
    EVENT_TYPE["CREATE"] = "CREATE";
    EVENT_TYPE["STARTTRANSPORT"] = "STARTTRANSPORT";
    EVENT_TYPE["ENDTRANSPORT"] = "ENDTRANSPORT";
    EVENT_TYPE["UPGRADE"] = "UPGRADE";
    EVENT_TYPE["REFINE"] = "REFINE";
    EVENT_TYPE["POOL"] = "POOL";
    EVENT_TYPE["BLEND"] = "BLEND";
    EVENT_TYPE["SPLIT"] = "SPLIT";
})(EVENT_TYPE = exports.EVENT_TYPE || (exports.EVENT_TYPE = {}));
