"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TRANSFORMATION_EVENT_TYPE = void 0;
var TRANSFORMATION_EVENT_TYPE;
(function (TRANSFORMATION_EVENT_TYPE) {
    TRANSFORMATION_EVENT_TYPE["UPGRADE"] = "Upgrade";
    TRANSFORMATION_EVENT_TYPE["SPLIT"] = "Split";
    TRANSFORMATION_EVENT_TYPE["POOL"] = "Pool";
    TRANSFORMATION_EVENT_TYPE["BLEND"] = "Blend";
    TRANSFORMATION_EVENT_TYPE["REFINE"] = "Refine";
})(TRANSFORMATION_EVENT_TYPE || (exports.TRANSFORMATION_EVENT_TYPE = TRANSFORMATION_EVENT_TYPE = {}));
