export enum CURRENT_EVENT_TYPE {
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  START_TRANSPORT = 'START_TRANSPORT',
  END_TRANSPORT = 'END_TRANSPORT',
  TRANSFORMATION_UPGRADE = 'TRANSFORMATION_UPGRADE',
  TRANSFORMATION_SPLIT = 'TRANSFORMATION_SPLIT',
  TRANSFORMATION_POOL = 'TRANSFORMATION_POOL',
  TRANSFORMATION_BLEND = 'TRANSFORMATION_BLEND',
  TRANSFORMATION_REFINE = 'TRANSFORMATION_REFINE',
  OWNERSHIP_TRANSFERED = 'OWNERSHIP_TRANSFERED',
  DELIVERY_SCHEDULED = 'DELIVERY_SCHEDULED'
}

export enum EVENT_TYPE {
  CREATE = 'CREATE',
  INSPECT = 'INSPECT',
  TRANSPORT_START = 'TRANSPORT_START',
  TRANSPORT_END = 'TRANSPORT_END',
  STORAGE_START = 'STORAGE_START',
  STORAGE_END = 'STORAGE_END',
  TRANSFORM_UPGRADE = 'TRANSFORM_UPGRADE',
  TRANSFORM_REFINE = 'TRANSFORM_REFINE',
  TRANSFORM_POOL = 'TRANSFORM_POOL',
  TRANSFORM_BLEND = 'TRANSFORM_BLEND',
  TRANSFORM_SPLIT = 'TRANSFORM_SPLIT',
  TRANSFER_OF_OWNERSHIP = 'TRANSFER_OF_OWNERSHIP',
  TRANSFER_OF_CUSTODY = 'TRANSFER_OF_CUSTODY',
  TRANSPORTATION_PLANNED = 'TRANSPORTATION_PLANNED',
  DELIVERY_SCHEDULED = 'DELIVERY_SCHEDULED',
  DELIVERY_TICKET = 'DELIVERY_TICKET',
  DISPLACEMENT = 'DISPLACEMENT',
  MONTHLY_PIPELINE_STATEMENT = 'MONTHLY_PIPELINE_STATEMENT',
  ADVANCE_MANIFEST = 'ADVANCE_MANIFEST',
  CREATE_ENTRY_NUMBER = 'CREATE_ENTRY_NUMBER',
  INTENT_TO_IMPORT = 'INTENT_TO_IMPORT',
  PRICE_STATEMENT = 'PRICE_STATEMENT',
  TSCA_CERTIFICATION = 'TSCA_CERTIFICATION'
}
