export var ORGANIZATION_ROLE;
(function (ORGANIZATION_ROLE) {
    ORGANIZATION_ROLE["CLIENT"] = "client";
    ORGANIZATION_ROLE["AGENCY"] = "agency";
    ORGANIZATION_ROLE["BROKER"] = "broker";
})(ORGANIZATION_ROLE || (ORGANIZATION_ROLE = {}));
