export const ExportProvinceCode = {
  ALBERTA: 'XA',
  AB: 'XA',
  BRITISH_COLUMBIA: 'XC',
  BC: 'XC',
  MANITOBA: 'XM',
  MB: 'XM',
  NEW_BRUNSWICK: 'XB',
  NB: 'XB',
  NEWFOUNDLAND_LABRADOR: 'XW',
  NF: 'XW',
  NORTHWEST_TERRITORIES: 'XT',
  NT: 'XT',
  NOVA_SCOTIA: 'XN',
  NS: 'XN',
  NUNAVUT: 'XV',
  NU: 'XV',
  ONTARIO: 'XO',
  ON: 'XO',
  PRINCE_EDWARD_ISLAND: 'XP',
  PE: 'XP',
  QUEBEC: 'XQ',
  QC: 'XQ',
  SASKATCHEWAN: 'XS',
  SK: 'XS',
  YUKON_TERRITORY: 'XY',
  YT: 'XY'
} as const
