export const ExportProvinceCode = {
  ALBERTA: 'XA',
  BRITISH_COLUMBIA: 'XC',
  MANITOBA: 'XM',
  NEW_BRUNSWICK: 'XB',
  NEWFOUNDLAND_LABRADOR: 'XW',
  NORTHWEST_TERRITORIES: 'XT',
  NOVA_SCOTIA: 'XN',
  NUNAVUT: 'XV',
  ONTARIO: 'XO',
  PRINCE_EDWARD_ISLAND: 'XP',
  QUEBEC: 'XQ',
  SASKATCHEWAN: 'XS',
  YUKON_TERRITORY: 'XY'
} as const
