export enum PRODUCT_STATUS {
  NEW = 'NEW',
  OWNERSHIP_TRANSFERRED = 'OWNERSHIP_TRANSFERRED',
  IN_TRANSIT = 'IN_TRANSIT',
  SCHEDULED = 'SCHEDULED',
  TRANSPORT_COMPLETED = 'TRANSPORT_COMPLETED',
  DELIVERED = 'DELIVERED',
  CONSUMED = 'CONSUMED',
  DECLARED = 'DECLARED',
  IN_STORAGE = 'IN_STORAGE',
  OUT_OF_STORAGE = 'OUT_OF_STORAGE',
  INSPECTED = 'INSPECTED',
  TRANSPORTATION_PLANNED = 'TRANSPORTATION_PLANNED',
  DELIVERY_SCHEDULED = 'DELIVERY_SCHEDULED',
  DISPLACEMENT = 'DISPLACEMENT',
  MONTHLY_PIPELINE_STATEMENT = 'MONTHLY_PIPELINE_STATEMENT'
}
