export enum PRODUCT_STATUS {
  NEW = 'NEW',
  SCHEDULED = 'SCHEDULED',
  TRANSPORT_DELAY = 'TRANSPORT_DELAY',
  TRANSPORT_COMPLETED = 'TRANSPORT_COMPLETED',
  OWNERSHIP_TRANSFERRED = 'OWNERSHIP_TRANSFERRED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CONSUMED = 'CONSUMED',
  DECLARED = 'DECLARED',
  INSPECTED = 'INSPECTED',
  IN_STORAGE = 'IN_STORAGE',
  OUT_OF_STORAGE = 'OUT_OF_STORAGE'
}
