import {
	PROOF_PURPOSE_TYPE as PROOF_PURPOSE_TYPE_BASE
} from 'mavennet-dto'

const enum PROOF_PURPOSE_TYPE_EXTEND {
}

export type PROOF_PURPOSE_TYPE = PROOF_PURPOSE_TYPE_BASE | PROOF_PURPOSE_TYPE_EXTEND