export declare const ExportProvinceCode: {
    readonly ALBERTA: "XA";
    readonly AB: "XA";
    readonly BRITISH_COLUMBIA: "XC";
    readonly BC: "XC";
    readonly MANITOBA: "XM";
    readonly MB: "XM";
    readonly NEW_BRUNSWICK: "XB";
    readonly NB: "XB";
    readonly NEWFOUNDLAND_LABRADOR: "XW";
    readonly NF: "XW";
    readonly NORTHWEST_TERRITORIES: "XT";
    readonly NT: "XT";
    readonly NOVA_SCOTIA: "XN";
    readonly NS: "XN";
    readonly NUNAVUT: "XV";
    readonly NU: "XV";
    readonly ONTARIO: "XO";
    readonly ON: "XO";
    readonly PRINCE_EDWARD_ISLAND: "XP";
    readonly PE: "XP";
    readonly QUEBEC: "XQ";
    readonly QC: "XQ";
    readonly SASKATCHEWAN: "XS";
    readonly SK: "XS";
    readonly YUKON_TERRITORY: "XY";
    readonly YT: "XY";
};
