"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JSON_TYPE = void 0;
var JSON_TYPE;
(function (JSON_TYPE) {
    JSON_TYPE["VERIFIABLE_CREDENTIAL"] = "VerifiableCredential";
    JSON_TYPE["CRUDE_OIL_PRODUCT"] = "CrudeOilProduct";
    JSON_TYPE["NATURAL_GAS_PRODUCT"] = "NaturalGasProduct";
    JSON_TYPE["PLACE"] = "Place";
    JSON_TYPE["GEO_COORDINATES"] = "GeoCoordinates";
    JSON_TYPE["POSTAL_ADDRESS"] = "PostalAddress";
    JSON_TYPE["PARCEL_DELIVERY"] = "ParcelDelivery";
    JSON_TYPE["PRODUCT"] = "Product";
    JSON_TYPE["ORGANIZATION"] = "Organization";
    JSON_TYPE["OBSERVATION"] = "Observation";
    JSON_TYPE["MEASURED_VALUE"] = "MeasuredValue";
    JSON_TYPE["QUANTITATIVE_VALUE"] = "QuantitativeValue";
    JSON_TYPE["MECHANICAL_PROPERTY"] = "MechanicalProperty";
    JSON_TYPE["CHEMICAL_PROPERTY"] = "ChemicalProperty";
    JSON_TYPE["GAS_PROPERTY"] = "GasProperty";
    JSON_TYPE["INBOND"] = "Inbond";
    JSON_TYPE["BILL_OF_LADING"] = "BillOfLading";
    JSON_TYPE["OG_BILL_OF_LADING"] = "OGBillOfLading";
    JSON_TYPE["ED25519_SIGNATURE_2018"] = "Ed25519Signature2018";
    JSON_TYPE["QP_IN_BOND_EVENT_CREDENTIAL"] = "QPInBondEventCredential";
})(JSON_TYPE = exports.JSON_TYPE || (exports.JSON_TYPE = {}));
