"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JSON_TYPE_METAL = exports.JSON_TYPE = void 0;
var mavennet_dto_1 = require("mavennet-dto");
Object.defineProperty(exports, "JSON_TYPE", { enumerable: true, get: function () { return mavennet_dto_1.JSON_TYPE; } });
var JSON_TYPE_METAL;
(function (JSON_TYPE_METAL) {
    JSON_TYPE_METAL["METAL_PRODUCT"] = "MetalProduct";
    JSON_TYPE_METAL["STEEL_PRODUCT"] = "SteelProduct";
    JSON_TYPE_METAL["CREATION_EVENT_CREDENTIAL"] = "CreationEventCredential";
    JSON_TYPE_METAL["EVENT_CREDENTIAL"] = "EventCredential";
    JSON_TYPE_METAL["PRODUCT_CREATION_EVENT_CREDENTIAL"] = "ProductCreationEventCredential";
    JSON_TYPE_METAL["TRANSFER_EVENT_CREDENTIAL"] = "TransferEventCredential";
    JSON_TYPE_METAL["TRANSFORM_EVENT_CREDENTIAL"] = "TransformEventCredential";
    JSON_TYPE_METAL["START_TRANSPORT_EVENT_CREDENTIAL"] = "StartTransportEventCredential";
    JSON_TYPE_METAL["END_TRANSPORT_EVENT_CREDENTIAL"] = "EndTransportEventCredential";
    JSON_TYPE_METAL["ADD_ENTRY_DETAILS_EVENT_CREDENTIAL"] = "AddEntryDetailsEventCredential";
    JSON_TYPE_METAL["MILL_TEST_CREDENTIAL"] = "MillTestCredential";
    JSON_TYPE_METAL["INSPECTION_REPORT"] = "InspectionReport";
})(JSON_TYPE_METAL = exports.JSON_TYPE_METAL || (exports.JSON_TYPE_METAL = {}));
