"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JSON_TYPE_NF = exports.JSON_TYPE = void 0;
var traceability_dto_1 = require("@mavennet/traceability-dto");
Object.defineProperty(exports, "JSON_TYPE", { enumerable: true, get: function () { return traceability_dto_1.JSON_TYPE; } });
var JSON_TYPE_NF;
(function (JSON_TYPE_NF) {
    JSON_TYPE_NF["VERIFIABLE_CREDENTIAL"] = "VerifiableCredential";
    JSON_TYPE_NF["CRUDE_OIL_PRODUCT"] = "CrudeOilProduct";
    JSON_TYPE_NF["NATURAL_GAS_PRODUCT"] = "NaturalGasProduct";
    JSON_TYPE_NF["OIL_AND_GAS_PRODUCT"] = "OilAndGasProduct";
    JSON_TYPE_NF["PLACE"] = "Place";
    JSON_TYPE_NF["GEO_COORDINATES"] = "GeoCoordinates";
    JSON_TYPE_NF["POSTAL_ADDRESS"] = "PostalAddress";
    JSON_TYPE_NF["PARCEL_DELIVERY"] = "ParcelDelivery";
    JSON_TYPE_NF["PRODUCT"] = "Product";
    JSON_TYPE_NF["ORGANIZATION"] = "Organization";
    JSON_TYPE_NF["OBSERVATION"] = "Observation";
    JSON_TYPE_NF["MEASURED_VALUE"] = "MeasuredValue";
    JSON_TYPE_NF["QUANTITATIVE_VALUE"] = "QuantitativeValue";
    JSON_TYPE_NF["MECHANICAL_PROPERTY"] = "MechanicalProperty";
    JSON_TYPE_NF["CHEMICAL_PROPERTY"] = "ChemicalProperty";
    JSON_TYPE_NF["GAS_PROPERTY"] = "GasProperty";
    JSON_TYPE_NF["INBOND"] = "Inbond";
    JSON_TYPE_NF["BILL_OF_LADING"] = "BillOfLading";
    JSON_TYPE_NF["OG_BILL_OF_LADING"] = "OGBillOfLading";
    JSON_TYPE_NF["ED25519_SIGNATURE_2018"] = "Ed25519Signature2018";
    JSON_TYPE_NF["QP_IN_BOND_EVENT_CREDENTIAL"] = "QPInBondEventCredential";
    JSON_TYPE_NF["MONTHLY_DELIVERY_STATEMENT"] = "MonthlyDeliveryStatement";
    JSON_TYPE_NF["DELIVERY_STATEMENT"] = "DeliveryStatement";
    JSON_TYPE_NF["DELIVERY_SCHEDULE"] = "DeliverySchedule";
    JSON_TYPE_NF["COMMODITY"] = "Commodity";
    JSON_TYPE_NF["OG_DELIVERY_TICKET"] = "OilAndGasDeliveryTicket";
    JSON_TYPE_NF["OG_DELIVERY_TICKET_CREDENTIAL"] = "OilAndGasDeliveryTicketCredential";
    JSON_TYPE_NF["MONTHLY_ADVANCE_MANIFEST_CREDENTIAL"] = "MonthlyAdvanceManifestCredential";
    JSON_TYPE_NF["MONTHLY_ADVANCE_MANIFEST"] = "MonthlyAdvanceManifest";
    JSON_TYPE_NF["PRICE_SPECIFICATION"] = "PriceSpecification";
    JSON_TYPE_NF["TSCA_CERTIFICATION_CREDENTIAL"] = "TSCACertificationCredential";
    JSON_TYPE_NF["TSCA_CERTIFICATION"] = "TSCACertification";
})(JSON_TYPE_NF = exports.JSON_TYPE_NF || (exports.JSON_TYPE_NF = {}));
