export { JSON_TYPE } from '@mavennet/traceability-dto';
export declare enum JSON_TYPE_NF {
    VERIFIABLE_CREDENTIAL = "VerifiableCredential",
    CRUDE_OIL_PRODUCT = "CrudeOilProduct",
    NATURAL_GAS_PRODUCT = "NaturalGasProduct",
    OIL_AND_GAS_PRODUCT = "OilAndGasProduct",
    PLACE = "Place",
    GEO_COORDINATES = "GeoCoordinates",
    POSTAL_ADDRESS = "PostalAddress",
    PARCEL_DELIVERY = "ParcelDelivery",
    PRODUCT = "Product",
    ORGANIZATION = "Organization",
    OBSERVATION = "Observation",
    MEASURED_VALUE = "MeasuredValue",
    QUANTITATIVE_VALUE = "QuantitativeValue",
    MECHANICAL_PROPERTY = "MechanicalProperty",
    CHEMICAL_PROPERTY = "ChemicalProperty",
    GAS_PROPERTY = "GasProperty",
    INBOND = "Inbond",
    BILL_OF_LADING = "BillOfLading",
    OG_BILL_OF_LADING = "OGBillOfLading",
    ED25519_SIGNATURE_2018 = "Ed25519Signature2018",
    QP_IN_BOND_EVENT_CREDENTIAL = "QPInBondEventCredential",
    MONTHLY_DELIVERY_STATEMENT = "MonthlyDeliveryStatement",
    DELIVERY_STATEMENT = "DeliveryStatement",
    DELIVERY_SCHEDULE = "DeliverySchedule",
    COMMODITY = "Commodity",
    OG_DELIVERY_TICKET = "OilAndGasDeliveryTicket",
    OG_DELIVERY_TICKET_CREDENTIAL = "OilAndGasDeliveryTicketCredential",
    MONTHLY_ADVANCE_MANIFEST_CREDENTIAL = "MonthlyAdvanceManifestCredential",
    MONTHLY_ADVANCE_MANIFEST = "MonthlyAdvanceManifest",
    MONTHLY_DELIVERY_STATEMENTS_CREDENTIAL = "MonthlyAggregatedDeliveryStatementsCredential",
    MONTHLY_DELIVERY_STATEMENTS = "MonthlyAggregatedDeliveryStatements",
    PRICE_SPECIFICATION = "PriceSpecification",
    TSCA_CERTIFICATION_CREDENTIAL = "TSCACertificationCredential",
    TSCA_CERTIFICATION = "TSCACertification"
}
